package com.bit.sfa.Models;

/**
 * Created by Sathiyaraja on 6/20/2018.
 */

public class CompanyBranch {
    private String FCOMPANYBRANCH_ID;
    private String FCOMPANYBRANCH_BRANCH_CODE;
    private String FCOMPANYBRANCH_RECORD_ID;
    private String FCOMPANYBRANCH_CSETTINGS_CODE;
    private String FCOMPANYBRANCH_NNUM_VAL;
    private String FCOMPANYBRANCH_NYEAR_VAL;
    private String FCOMPANYBRANCH_NMONTH_VAL;

    public String getFCOMPANYBRANCH_ID() {
        return FCOMPANYBRANCH_ID;
    }
    public void setFCOMPANYBRANCH_ID(String fCOMPANYBRANCH_ID) {
        FCOMPANYBRANCH_ID = fCOMPANYBRANCH_ID;
    }
    public String getFCOMPANYBRANCH_BRANCH_CODE() {
        return FCOMPANYBRANCH_BRANCH_CODE;
    }
    public void setFCOMPANYBRANCH_BRANCH_CODE(String fCOMPANYBRANCH_BRANCH_CODE) {
        FCOMPANYBRANCH_BRANCH_CODE = fCOMPANYBRANCH_BRANCH_CODE;
    }
    public String getFCOMPANYBRANCH_RECORD_ID() {
        return FCOMPANYBRANCH_RECORD_ID;
    }
    public void setFCOMPANYBRANCH_RECORD_ID(String fCOMPANYBRANCH_RECORD_ID) {
        FCOMPANYBRANCH_RECORD_ID = fCOMPANYBRANCH_RECORD_ID;
    }
    public String getFCOMPANYBRANCH_CSETTINGS_CODE() {
        return FCOMPANYBRANCH_CSETTINGS_CODE;
    }
    public void setFCOMPANYBRANCH_CSETTINGS_CODE(
            String fCOMPANYBRANCH_CSETTINGS_CODE) {
        FCOMPANYBRANCH_CSETTINGS_CODE = fCOMPANYBRANCH_CSETTINGS_CODE;
    }
    public String getFCOMPANYBRANCH_NNUM_VAL() {
        return FCOMPANYBRANCH_NNUM_VAL;
    }
    public void setFCOMPANYBRANCH_NNUM_VAL(String fCOMPANYBRANCH_NNUM_VAL) {
        FCOMPANYBRANCH_NNUM_VAL = fCOMPANYBRANCH_NNUM_VAL;
    }
    public String getFCOMPANYBRANCH_NYEAR_VAL() {
        return FCOMPANYBRANCH_NYEAR_VAL;
    }
    public void setFCOMPANYBRANCH_NYEAR_VAL(String fCOMPANYBRANCH_NYEAR_VAL) {
        FCOMPANYBRANCH_NYEAR_VAL = fCOMPANYBRANCH_NYEAR_VAL;
    }
    public String getFCOMPANYBRANCH_NMONTH_VAL() {
        return FCOMPANYBRANCH_NMONTH_VAL;
    }
    public void setFCOMPANYBRANCH_NMONTH_VAL(String fCOMPANYBRANCH_NMONTH_VAL) {
        FCOMPANYBRANCH_NMONTH_VAL = fCOMPANYBRANCH_NMONTH_VAL;
    }
}
