package com.bit.sfa.Models;

public class SalOrdPrintPre {

	private String SAL_PRINT_REF_NO;
	private String SAL_PRINT_DEBCODE;
	private String SAL_PRINT_DEBNAME;
	private String SAL_PRINT_DEBADD1;
	private String SAL_PRINT_DEBADD2;
	private String SAL_PRINT_DEBADD3;
	private String SAL_PRINT_DEBTELE;
	private String SAL_PRINT_TXN_DATE;
	private String SAL_PRINT_DELVIDATE;
	private String SAL_PRINT_REMARKS;
	private String SAL_PRINT_CASE_QTY;
	private String SAL_PRINT_PIECE_QTY;
	private String SAL_PRINT_SELL_PRICE;
	private String SAL_PRINT_TOTAL_UNIT_QTY;
	private String SAL_PRINT_ITEMNAME;
	private String SAL_PRINT_DISAMT_DETAIL;
	private String SAL_PRINT_TOTAL_DIS_AMT;
	private String SAL_PRINT_TOTAL_AMT;
	private String SAL_PRINT_BDIS_AMT;
	private String SAL_PRINT_DETAIL_DISPER;
	private String SAL_PRINT_TOTALDIS_HEAD;
	private String SAL_PRINT_TOTALDIS_HEAD_B;
	private String SAL_PRINT_TRAN_TYPE;
	private String SAL_PRINT_SEQNO;
	private String SAL_PRINT_ITEM_DIS;
	private String SAL_PRINT_ITEMCODE;
	private String SAL_PRINT_DETAIL_AMT;
	private String PRINT_TOTALAMT_HEAD;
	private String PRINT_TOTALMKT_AMT;
	private String SAL_PRINT_UNITS;
	private String SAL_DIS_VALUE_AMT;
	private String SAL_HEAD_DIS;
	private String SAL_HEAD_DIS_CALL;
	
	public String getSAL_PRINT_REF_NO() {
		return SAL_PRINT_REF_NO;
	}
	public void setSAL_PRINT_REF_NO(String sAL_PRINT_REF_NO) {
		SAL_PRINT_REF_NO = sAL_PRINT_REF_NO;
	}
	public String getSAL_PRINT_DEBADD1() {
		return SAL_PRINT_DEBADD1;
	}
	public void setSAL_PRINT_DEBADD1(String sAL_PRINT_DEBADD1) {
		SAL_PRINT_DEBADD1 = sAL_PRINT_DEBADD1;
	}
	public String getSAL_PRINT_DEBCODE() {
		return SAL_PRINT_DEBCODE;
	}
	public void setSAL_PRINT_DEBCODE(String sAL_PRINT_DEBCODE) {
		SAL_PRINT_DEBCODE = sAL_PRINT_DEBCODE;
	}
	public String getSAL_PRINT_DEBNAME() {
		return SAL_PRINT_DEBNAME;
	}
	public void setSAL_PRINT_DEBNAME(String sAL_PRINT_DEBNAME) {
		SAL_PRINT_DEBNAME = sAL_PRINT_DEBNAME;
	}
	public String getSAL_PRINT_DEBADD3() {
		return SAL_PRINT_DEBADD3;
	}
	public void setSAL_PRINT_DEBADD3(String sAL_PRINT_DEBADD3) {
		SAL_PRINT_DEBADD3 = sAL_PRINT_DEBADD3;
	}
	public String getSAL_PRINT_DELVIDATE() {
		return SAL_PRINT_DELVIDATE;
	}
	public void setSAL_PRINT_DELVIDATE(String sAL_PRINT_DELVIDATE) {
		SAL_PRINT_DELVIDATE = sAL_PRINT_DELVIDATE;
	}
	public String getSAL_PRINT_CASE_QTY() {
		return SAL_PRINT_CASE_QTY;
	}
	public void setSAL_PRINT_CASE_QTY(String sAL_PRINT_CASE_QTY) {
		SAL_PRINT_CASE_QTY = sAL_PRINT_CASE_QTY;
	}
	public String getSAL_PRINT_ITEMNAME() {
		return SAL_PRINT_ITEMNAME;
	}
	public void setSAL_PRINT_ITEMNAME(String sAL_PRINT_ITEMNAME) {
		SAL_PRINT_ITEMNAME = sAL_PRINT_ITEMNAME;
	}
	public String getSAL_PRINT_TOTAL_AMT() {
		return SAL_PRINT_TOTAL_AMT;
	}
	public void setSAL_PRINT_TOTAL_AMT(String sAL_PRINT_TOTAL_AMT) {
		SAL_PRINT_TOTAL_AMT = sAL_PRINT_TOTAL_AMT;
	}
	public String getSAL_PRINT_DEBADD2() {
		return SAL_PRINT_DEBADD2;
	}
	public void setSAL_PRINT_DEBADD2(String sAL_PRINT_DEBADD2) {
		SAL_PRINT_DEBADD2 = sAL_PRINT_DEBADD2;
	}
	public String getSAL_PRINT_TXN_DATE() {
		return SAL_PRINT_TXN_DATE;
	}
	public void setSAL_PRINT_TXN_DATE(String sAL_PRINT_TXN_DATE) {
		SAL_PRINT_TXN_DATE = sAL_PRINT_TXN_DATE;
	}
	public String getSAL_PRINT_REMARKS() {
		return SAL_PRINT_REMARKS;
	}
	public void setSAL_PRINT_REMARKS(String sAL_PRINT_REMARKS) {
		SAL_PRINT_REMARKS = sAL_PRINT_REMARKS;
	}
	public String getSAL_PRINT_PIECE_QTY() {
		return SAL_PRINT_PIECE_QTY;
	}
	public void setSAL_PRINT_PIECE_QTY(String sAL_PRINT_PIECE_QTY) {
		SAL_PRINT_PIECE_QTY = sAL_PRINT_PIECE_QTY;
	}
	public String getSAL_PRINT_BDIS_AMT() {
		return SAL_PRINT_BDIS_AMT;
	}
	public void setSAL_PRINT_BDIS_AMT(String sAL_PRINT_BDIS_AMT) {
		SAL_PRINT_BDIS_AMT = sAL_PRINT_BDIS_AMT;
	}
	public String getSAL_PRINT_TRAN_TYPE() {
		return SAL_PRINT_TRAN_TYPE;
	}
	public void setSAL_PRINT_TRAN_TYPE(String sAL_PRINT_TRAN_TYPE) {
		SAL_PRINT_TRAN_TYPE = sAL_PRINT_TRAN_TYPE;
	}

	public String getSAL_PRINT_SEQNO() {
		return SAL_PRINT_SEQNO;
	}
	public void setSAL_PRINT_SEQNO(String sAL_PRINT_SEQNO) {
		SAL_PRINT_SEQNO = sAL_PRINT_SEQNO;
	}
	public String getSAL_PRINT_DEBTELE() {
		return SAL_PRINT_DEBTELE;
	}
	public void setSAL_PRINT_DEBTELE(String sAL_PRINT_DEBTELE) {
		SAL_PRINT_DEBTELE = sAL_PRINT_DEBTELE;
	}
	public String getSAL_PRINT_DISAMT_DETAIL() {
		return SAL_PRINT_DISAMT_DETAIL;
	}
	public void setSAL_PRINT_DISAMT_DETAIL(String sAL_PRINT_DISAMT_DETAIL) {
		SAL_PRINT_DISAMT_DETAIL = sAL_PRINT_DISAMT_DETAIL;
	}
	public String getSAL_PRINT_TOTALDIS_HEAD() {
		return SAL_PRINT_TOTALDIS_HEAD;
	}
	public void setSAL_PRINT_TOTALDIS_HEAD(String sAL_PRINT_TOTALDIS_HEAD) {
		SAL_PRINT_TOTALDIS_HEAD = sAL_PRINT_TOTALDIS_HEAD;
	}
	public String getSAL_PRINT_DETAIL_DISPER() {
		return SAL_PRINT_DETAIL_DISPER;
	}
	public void setSAL_PRINT_DETAIL_DISPER(String sAL_PRINT_DETAIL_DISPER) {
		SAL_PRINT_DETAIL_DISPER = sAL_PRINT_DETAIL_DISPER;
	}
	public String getSAL_PRINT_ITEMCODE() {
		return SAL_PRINT_ITEMCODE;
	}
	public void setSAL_PRINT_ITEMCODE(String sAL_PRINT_ITEMCODE) {
		SAL_PRINT_ITEMCODE = sAL_PRINT_ITEMCODE;
	}
	public String getSAL_PRINT_SELL_PRICE() {
		return SAL_PRINT_SELL_PRICE;
	}
	public void setSAL_PRINT_SELL_PRICE(String sAL_PRINT_SELL_PRICE) {
		SAL_PRINT_SELL_PRICE = sAL_PRINT_SELL_PRICE;
	}
	public String getSAL_PRINT_TOTAL_UNIT_QTY() {
		return SAL_PRINT_TOTAL_UNIT_QTY;
	}
	public void setSAL_PRINT_TOTAL_UNIT_QTY(String sAL_PRINT_TOTAL_UNIT_QTY) {
		SAL_PRINT_TOTAL_UNIT_QTY = sAL_PRINT_TOTAL_UNIT_QTY;
	}
	public String getSAL_PRINT_DETAIL_AMT() {
		return SAL_PRINT_DETAIL_AMT;
	}
	public void setSAL_PRINT_DETAIL_AMT(String sAL_PRINT_DETAIL_AMT) {
		SAL_PRINT_DETAIL_AMT = sAL_PRINT_DETAIL_AMT;
	}
	public String getSAL_PRINT_TOTALDIS_HEAD_B() {
		return SAL_PRINT_TOTALDIS_HEAD_B;
	}
	public void setSAL_PRINT_TOTALDIS_HEAD_B(String sAL_PRINT_TOTALDIS_HEAD_B) {
		SAL_PRINT_TOTALDIS_HEAD_B = sAL_PRINT_TOTALDIS_HEAD_B;
	}
	public String getPRINT_TOTALAMT_HEAD() {
		return PRINT_TOTALAMT_HEAD;
	}
	public void setPRINT_TOTALAMT_HEAD(String pRINT_TOTALAMT_HEAD) {
		PRINT_TOTALAMT_HEAD = pRINT_TOTALAMT_HEAD;
	}
	public String getSAL_PRINT_ITEM_DIS() {
		return SAL_PRINT_ITEM_DIS;
	}
	public void setSAL_PRINT_ITEM_DIS(String sAL_PRINT_ITEM_DIS) {
		SAL_PRINT_ITEM_DIS = sAL_PRINT_ITEM_DIS;
	}
	public String getPRINT_TOTALMKT_AMT() {
		return PRINT_TOTALMKT_AMT;
	}
	public void setPRINT_TOTALMKT_AMT(String pRINT_TOTALMKT_AMT) {
		PRINT_TOTALMKT_AMT = pRINT_TOTALMKT_AMT;
	}
	public String getSAL_PRINT_TOTAL_DIS_AMT() {
		return SAL_PRINT_TOTAL_DIS_AMT;
	}
	public void setSAL_PRINT_TOTAL_DIS_AMT(String sAL_PRINT_TOTAL_DIS_AMT) {
		SAL_PRINT_TOTAL_DIS_AMT = sAL_PRINT_TOTAL_DIS_AMT;
	}
	public String getSAL_PRINT_UNITS() {
		return SAL_PRINT_UNITS;
	}
	public void setSAL_PRINT_UNITS(String sAL_PRINT_UNITS) {
		SAL_PRINT_UNITS = sAL_PRINT_UNITS;
	}
	public String getSAL_DIS_VALUE_AMT() {
		return SAL_DIS_VALUE_AMT;
	}
	public void setSAL_DIS_VALUE_AMT(String sAL_DIS_VALUE_AMT) {
		SAL_DIS_VALUE_AMT = sAL_DIS_VALUE_AMT;
	}
	public String getSAL_HEAD_DIS() {
		return SAL_HEAD_DIS;
	}
	public void setSAL_HEAD_DIS(String sAL_HEAD_DIS) {
		SAL_HEAD_DIS = sAL_HEAD_DIS;
	}
	public String getSAL_HEAD_DIS_CALL() {
		return SAL_HEAD_DIS_CALL;
	}
	public void setSAL_HEAD_DIS_CALL(String sAL_HEAD_DIS_CALL) {
		SAL_HEAD_DIS_CALL = sAL_HEAD_DIS_CALL;
	}
	

}
